global using Microsoft.EntityFrameworkCore.Storage;
global using System;
global using System.Linq;
global using Microsoft.Extensions.Configuration;
global using BJM.DVDCentral.PL2.Data;
global using BJM.DVDCentral.PL2.Entities;
global using BJM.DVDCentral.BL.Models;
global using System.Collections.Generic;
global using Microsoft.EntityFrameworkCore;
